import mongoose from "mongoose";

const adminSchema = new mongoose.Schema(
    {
        firstName: { type: String, required: true },
        lastName: { type: String, required: true },

        emailOrMobile: { type: String, required: true, unique: true },

        otp: { type: String },              // temporary OTP (string to support leading 0s)
        otpExpiresAt: { type: Date },       // expiry time

        isActive: { type: Boolean, default: true }, // only active admins can login
    },
    { timestamps: true } // auto-adds createdAt & updatedAt
);

// createdAt & updatedAt auto-generated by MongoDB
export default mongoose.model("Admin", adminSchema);
